import { setAppTitle } from '@/lib/utils';
import { Metadata } from 'next/types';
import LoginForm from './components/LoginForm';

export const metadata: Metadata = {
	title: setAppTitle('Login'),
	description: 'Generated by create next app',
};

export default function page() {
	return (
		<div className="flex flex-col w-full h-full md:my-auto items-center justify-center">
			<h1 className="scroll-m-20 text-4xl font-extrabold tracking-tight lg:text-5xl text-center">
				Login to Your Account
			</h1>

			<LoginForm />
		</div>
	);
}
