import { APP_NAME } from '@/constants';
import { setAppTitle } from '@/lib/utils';
import { Metadata } from 'next/types';

export const metadata: Metadata = {
	title: setAppTitle('welcome'),
	description: 'Generated by create next app',
};

const page = () => {
	return (
		<>
			<h1 className="scroll-m-20 text-4xl font-extrabold tracking-tight lg:text-5xl">
				Welcome to {APP_NAME}!
			</h1>
		</>
	);
};

export default page;
